apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/    
